apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: home.arpa
spec:
  secretName: home.arpa-selfsigned-wildcard
  issuerRef:
    kind: ClusterIssuer
    name: cluster-selfsigned-issuer
  dnsNames:
  - "home.arpa"
  - "*.home.arpa"
  - "ops.home.arpa"
  - "*.ops.home.arpa"
  - "apps.home.arpa"
  - "*.apps.home.arpa"
